# Generated by Django 5.1.4 on 2025-01-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='description',
        ),
        migrations.RemoveField(
            model_name='director',
            name='price',
        ),
    ]
