# Generated by Django 5.1.4 on 2025-01-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_director_description_remove_director_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.director')),
            ],
        ),
    ]
